#!/bin/bash

# Failed Deployment Troubleshooter
# Helps diagnose and fix deployment failures

echo "╔════════════════════════════════════════════════════════╗"
echo "║         Deployment Failure Troubleshooter             ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${RED}🚨 DEPLOYMENT FAILED${NC}"
echo ""
echo "Deployment #44 failed at 9:40 AM (2 min 57 sec)"
echo "Commit: f0725bb - Fix: Frontend/backend sync..."
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}📊 Common Deployment Failures & Solutions${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${RED}Common Issue 1: Build Errors${NC}"
echo ""
echo "Symptoms:"
echo "  • 'npm ERR!' in logs"
echo "  • 'Failed to compile'"
echo "  • TypeScript errors"
echo ""
echo "Likely causes:"
echo "  • Missing dependencies"
echo "  • TypeScript compilation errors"
echo "  • Import path issues"
echo ""
echo "How to check:"
echo "  1. Open Amplify Console build logs"
echo "  2. Look for 'BUILD' phase"
echo "  3. Find red error messages"
echo ""
echo "Quick fixes:"
echo "  • Check package.json dependencies"
echo "  • Run 'npm install' locally"
echo "  • Fix TypeScript errors"
echo ""

echo "─────────────────────────────────────────────────────────"
echo ""

echo -e "${RED}Common Issue 2: Backend Deployment Errors${NC}"
echo ""
echo "Symptoms:"
echo "  • 'Amplify push failed'"
echo "  • Backend build errors"
echo "  • Lambda deployment failed"
echo ""
echo "Likely causes:"
echo "  • amplify_outputs.json issues"
echo "  • Backend schema changes"
echo "  • IAM permission issues"
echo ""
echo "Quick fixes:"
echo "  • Check amplify/backend files"
echo "  • Verify Lambda handler code"
echo "  • Check IAM roles"
echo ""

echo "─────────────────────────────────────────────────────────"
echo ""

echo -e "${RED}Common Issue 3: Environment Issues${NC}"
echo ""
echo "Symptoms:"
echo "  • 'Node not found'"
echo "  • Version mismatch"
echo "  • Package manager errors"
echo ""
echo "Likely causes:"
echo "  • Node.js version incompatibility"
echo "  • npm/pnpm configuration"
echo "  • Missing build commands"
echo ""
echo "Quick fixes:"
echo "  • Check amplify.yml node version"
echo "  • Verify build commands"
echo "  • Update package.json"
echo ""

echo "─────────────────────────────────────────────────────────"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}🔍 IMMEDIATE ACTIONS${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "1. Check Build Logs in Amplify Console:"
echo "   https://eu-central-1.console.aws.amazon.com/amplify"
echo ""
echo "   Look for:"
echo "   • Red error messages"
echo "   • Failed phase (Provision/Build/Deploy)"
echo "   • Specific error codes"
echo ""

echo "2. Check CloudWatch Logs:"
echo "   https://eu-central-1.console.aws.amazon.com/cloudwatch"
echo ""

echo "3. Review Recent Changes:"
echo "   • What files changed in commit f0725bb?"
echo "   • Any new dependencies?"
echo "   • Configuration changes?"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}🛠️  TROUBLESHOOTING STEPS${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "Step 1: Get Error Details"
echo ""
echo "a) In Amplify Console:"
echo "   • Click on failed deployment #44"
echo "   • Expand each phase"
echo "   • Copy error messages"
echo ""
echo "b) Look for these patterns:"
echo "   • 'Error:' lines"
echo "   • 'FAILED' status"
echo "   • Stack traces"
echo ""

echo "Step 2: Test Locally"
echo ""
echo "Try building locally to reproduce:"
echo "  cd /home/tbaltzakis/my-portfolio-aws"
echo "  npm install"
echo "  npm run build"
echo ""
echo "If local build fails, fix errors before redeploying"
echo ""

echo "Step 3: Check Key Files"
echo ""
echo "Verify these files are correct:"
echo "  • package.json - all dependencies listed"
echo "  • next.config.ts - valid configuration"
echo "  • amplify.yml - correct build commands"
echo "  • tsconfig.json - valid TypeScript config"
echo ""

echo "Step 4: Review Recent Changes"
echo ""
echo "What changed in this commit?"
echo "  git diff HEAD~1 HEAD"
echo ""
echo "Focus on:"
echo "  • New imports"
echo "  • Configuration changes"
echo "  • New dependencies"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}🔧 LIKELY FIXES${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "Based on your recent changes, check:"
echo ""

echo "1. lib/amplify-client-config.ts"
echo "   • Verify import paths are correct"
echo "   • Check amplify_outputs.json exists"
echo "   • Ensure proper 'use client' directive"
echo ""

echo "2. components/Contact.tsx"
echo "   • Check import of amplify-client-config"
echo "   • Verify relative path: '../lib/amplify-client-config'"
echo "   • Ensure GraphQL mutation is correct"
echo ""

echo "3. Build Configuration"
echo "   • Check amplify.yml has correct commands"
echo "   • Verify Node.js version specified"
echo "   • Check if all scripts exist in package.json"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}📋 CHECKLIST${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "Before redeploying, verify:"
echo ""
echo "  [ ] Reviewed Amplify Console error logs"
echo "  [ ] Identified specific error message"
echo "  [ ] Tested build locally (if possible)"
echo "  [ ] Fixed any TypeScript errors"
echo "  [ ] Verified all import paths"
echo "  [ ] Checked amplify.yml configuration"
echo "  [ ] Committed fix to git"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}🚀 REDEPLOY PROCESS${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "After fixing the issue:"
echo ""
echo "1. Stage your fixes:"
echo "   git add ."
echo ""
echo "2. Commit with descriptive message:"
echo "   git commit -m 'Fix: [describe the fix]'"
echo ""
echo "3. Push to trigger new deployment:"
echo "   git push"
echo ""
echo "4. Monitor in Amplify Console"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${RED}⚠️  IMPORTANT${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "To properly diagnose this, we need:"
echo ""
echo "1. FULL BUILD LOGS from Amplify Console"
echo "   • Go to: https://eu-central-1.console.aws.amazon.com/amplify"
echo "   • Click deployment #44"
echo "   • Copy the complete error message"
echo ""
echo "2. Specific phase that failed:"
echo "   • Provision?"
echo "   • Build?"
echo "   • Deploy?"
echo ""
echo "3. Error message text"
echo ""

echo -e "${YELLOW}Please share the error logs so I can provide specific fixes!${NC}"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}📞 Next Steps${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""

echo "Get the error details by:"
echo ""
echo "1. Opening Amplify Console"
echo "   https://eu-central-1.console.aws.amazon.com/amplify"
echo ""
echo "2. Click on deployment #44 (Failed)"
echo ""
echo "3. Look at each phase and find the red error"
echo ""
echo "4. Share the error message"
echo ""
echo "Then I can provide an exact fix! 🔧"
echo ""
