#!/bin/bash

# Amplify Build Log Analyzer
# Analyzes and explains Amplify build logs

echo "╔════════════════════════════════════════════════════════╗"
echo "║         Amplify Build Log Analyzer                    ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}Reading your deployment logs...${NC}"
echo ""

# Parse the log snippet you provided
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ PROVISION Phase (Complete)${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✓${NC} Build environment: 8GiB Memory, 4vCPUs, 128GB Disk"
echo -e "${GREEN}✓${NC} Git provider SSH keys retrieved"
echo -e "${GREEN}✓${NC} Repository cloned: my-portfolio-aws"
echo -e "${GREEN}✓${NC} Switched to commit: f0725bb"
echo -e "   ${CYAN}(Your latest fixes!)${NC}"
echo -e "${GREEN}✓${NC} Environment cache retrieved"
echo -e "${GREEN}✓${NC} Backend environment 'master' connected"
echo ""
echo -e "${YELLOW}⏱${NC}  Time elapsed: ~3 minutes"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}⏳ BUILD Phase (In Progress)${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo "Expected steps:"
echo -e "${CYAN}1.${NC} npm install (dependencies)"
echo -e "${CYAN}2.${NC} npm run build (Next.js build)"
echo -e "${CYAN}3.${NC} Create static output in /out directory"
echo ""
echo -e "${YELLOW}This typically takes 5-8 minutes total${NC}"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}📊 What's Happening Now${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo "Amplify is:"
echo -e "${CYAN}•${NC} Installing Node.js dependencies (node_modules)"
echo -e "${CYAN}•${NC} Running Next.js build process"
echo -e "${CYAN}•${NC} Compiling TypeScript to JavaScript"
echo -e "${CYAN}•${NC} Optimizing images and assets"
echo -e "${CYAN}•${NC} Generating static HTML pages"
echo -e "${CYAN}•${NC} Creating the /out directory for deployment"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✨ What's New in This Deployment${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✓${NC} Fixed frontend/backend sync issues"
echo -e "${GREEN}✓${NC} Added client-side Amplify configuration"
echo -e "${GREEN}✓${NC} Unified contact form mutation approach"
echo -e "${GREEN}✓${NC} Contact → AppSync → Lambda → DynamoDB + SES"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}⏭️  Next Phases${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}After BUILD completes:${NC}"
echo ""
echo -e "${CYAN}3. DEPLOY Phase${NC} (~2 minutes)"
echo "   • Upload static files to CDN"
echo "   • Deploy backend changes"
echo "   • Update CloudFront distribution"
echo ""
echo -e "${CYAN}4. VERIFY Phase${NC} (~1 minute)"
echo "   • Health checks"
echo "   • Final validation"
echo "   • Site goes live!"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}📝 Monitoring Tips${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo "In Amplify Console, watch for:"
echo -e "${GREEN}✓${NC} Each phase turning green"
echo -e "${GREEN}✓${NC} BUILD showing 'npm run build' output"
echo -e "${GREEN}✓${NC} No red error messages"
echo ""
echo "Look for these success indicators:"
echo -e "${GREEN}•${NC} 'Creating an optimized production build...'"
echo -e "${GREEN}•${NC} 'Compiled successfully'"
echo -e "${GREEN}•${NC} 'Generating static pages'"
echo -e "${GREEN}•${NC} 'Export successful'"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${RED}🚨 Warning Signs to Watch For${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo "If you see these, there may be issues:"
echo -e "${RED}✗${NC} 'npm ERR!' - Dependency problems"
echo -e "${RED}✗${NC} 'Type error' - TypeScript compilation failed"
echo -e "${RED}✗${NC} 'Failed to compile' - Build errors"
echo -e "${RED}✗${NC} 'Build failed' - General build failure"
echo ""
echo "If errors occur, check:"
echo "1. Full build logs in Amplify Console"
echo "2. Run 'npm run build' locally to debug"
echo "3. Check ./health-check.sh for local issues"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}🔗 Useful Links${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo "Amplify Console:"
echo "  https://eu-central-1.console.aws.amazon.com/amplify"
echo ""
echo "CloudWatch Logs (after deployment):"
echo "  https://eu-central-1.console.aws.amazon.com/cloudwatch"
echo ""
echo "Your GitHub Commit:"
echo "  https://github.com/Themis128/my-portfolio-aws/commit/f0725bb"
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}⏰ Estimated Completion Time${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Started: ~3 minutes ago"
echo -e "${YELLOW}Expected completion: 7-12 more minutes${NC}"
echo ""
echo "Total deployment time: ~10-15 minutes"
echo ""
echo -e "${GREEN}✨ Your site will be live soon!${NC}"
echo ""
